SELECT COMPANY.COMPANY_CODE, COMPANY.FOUNDER, COUNT(DISTINCT(LEAD_MANAGER.LEAD_MANAGER_CODE)), 
COUNT(DISTINCT(SENIOR_MANAGER.SENIOR_MANAGER_CODE)), COUNT(DISTINCT(MANAGER.MANAGER_CODE)), COUNT(DISTINCT(EMPLOYEE.EMPLOYEE_CODE))
FROM COMPANY JOIN LEAD_MANAGER ON COMPANY.COMPANY_CODE = LEAD_MANAGER.COMPANY_CODE JOIN SENIOR_MANAGER ON COMPANY.COMPANY_CODE = SENIOR_MANAGER.COMPANY_CODE
 JOIN MANAGER ON MANAGER.COMPANY_CODE = COMPANY.COMPANY_CODE JOIN EMPLOYEE ON EMPLOYEE.COMPANY_CODE = COMPANY.COMPANY_CODE
GROUP BY COMPANY.COMPANY_CODE, COMPANY.FOUNDER
ORDER BY COMPANY.COMPANY_CODE

/*
여러개의 테이블을 JOIN할 때 고민없이 쭉쭉 JOIN을 연결해도 된다.
만약 group by company.founder를 제거한다면 오류가 발생한다, why?
-> founder는 하나의 company_code에 여러개 존재하며, group by company_code를 실행할 경우 select company.founder를 처리할 수 없기 때문
그래서 group by에 company_code와 founder를 모두 넣어서 오류가 발생하지 않도록 한다.
만약 founder가 count(distinct(founder))의 집계 형식이었다면 groupby에 없어도 무관
*/