WITH TEMP_TABLE AS 
(
SELECT HACKER_ID, NAME, COUNT(*) AS TOTAL_NUMBER, COUNT(*) OVER (PARTITION BY COUNT(*)) AS DUPLICATE
FROM HACKERS NATURAL JOIN CHALLENGES
GROUP BY HACKER_ID, NAME
ORDER BY TOTAL_NUMBER DESC, HACKER_ID
)

SELECT HACKER_ID, NAME, TOTAL_NUMBER
FROM TEMP_TABLE
WHERE DUPLICATE = 1 OR TOTAL_NUMBER = 
(
SELECT MAX(TOTAL_NUMBER) FROM TEMP_TABLE
)

/*
WITH AS 문으로 새로운 테이블을 만들 수 있다.
COUNT를 다시 COUNT하기 위해선 COUNT(*) OVER (PARTITION BY COUNT(*))를 활용하면 된다.
*/