SELECT T2.ID, T1.AGE, T1.MIN_COINS, T1.POWER
FROM (
SELECT MIN(COINS_NEEDED) AS MIN_COINS, AGE, POWER, CODE
FROM WANDS NATURAL JOIN WANDS_PROPERTY
WHERE IS_EVIL = 0
GROUP BY AGE, POWER, CODE) T1 JOIN WANDS T2 ON T1.CODE = T2.CODE AND T1.MIN_COINS = T2.COINS_NEEDED
ORDER BY POWER DESC, AGE DESC

/*
NATURAL JOIN을 사용하면 겹치는 COLUMN NAME을 기반으로 JOIN한다.
해당 문제에서 중요한 부분은 GROUP BY AGE, POWER가 필수적이지만 ID값을 가져와야 하기 때문에 GROUP BY를 외부 SELECT문에서 사용할 수 없다는 것
내부 SELECT문에서 자료를 미리 처리해서 정리한 후, 결과를 도출하는 과정이 필요한 문제
*/